version: '3.9'

services:
  redpanda-0:
    container_name: redpanda-0
    hostname: redpanda-0
    env_file:
      - default.env
    environment:
      - IS_LEADER=yes
      - RACK_NAME=Alpha
    build:
      args:
        - APP_VERSION=21.11.9-1-ad9c5af5
        - APP_REDPANDA_REPO=nzc4ZYQK3WRGd9sy
      context: ./redpanda
#    volumes:
#      - redpanda01-data:/opt/redpanda/data:rw
  redpanda-1:
    container_name: redpanda-1
    hostname: redpanda-1
    env_file:
      - default.env
    environment:
      #- IS_LEADER=yes
      - RACK_NAME=Beta
    build:
      args:
        - APP_VERSION=21.11.9-1-ad9c5af5
        - APP_REDPANDA_REPO=nzc4ZYQK3WRGd9sy
      context: ./redpanda
#    volumes:
#      - redpanda02-data:/opt/redpanda/data:rw
  redpanda-2:
    container_name: redpanda-2
    hostname: redpanda-2
    env_file:
      - default.env
    environment:
      #- IS_LEADER=yes
      - RACK_NAME=Gamma
    build:
      args:
        - APP_VERSION=21.11.9-1-ad9c5af5
        - APP_REDPANDA_REPO=nzc4ZYQK3WRGd9sy
      context: ./redpanda
#    volumes:
#      - redpanda03-data:/opt/redpanda/data:rw

#volumes:
#  redpanda01-data:
#  redpanda02-data:
#  redpanda03-data:
